version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - VIRTUAL_HOST=api.powerit.loc
    volumes:
      - .:/var/www/html:delegated
    networks:
      - backend
      - proxy_proxy

  postgres:
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres

volumes:
  postgres:
    driver: local

networks:
  backend:
    driver: bridge
  proxy_proxy:
    external: true
