version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    environment:
      - VIRTUAL_HOST=api.server.loc
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - web

  postgres:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    networks:
      - web
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
      volumes:
        - ~/nginx/vhost.d:/etc/nginx/vhost.d:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
      restart: always
      networks:
        - web

networks:
  web:
    external: true


